---
- name: Setup bastion host 
  hosts: localhost
  connection: local
  gather_facts: no 
  tasks:
    - name: Import vpc setup variable 
      include_vars: vars/vpc_setup

    - name: Import vpc setup variable
      include_vars: vars/vpc-output_vars 

    - name: Create ec2 key
      ec2_key:
        name: bastion_key
        region: "{{ region }}"
      register: key_out

    - name: Save private key into file bastion_key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion_key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create security group for bastion host 
      ec2_group:
        name: bastion_host_sg
        description: Allow port 22 from everywhere and all port with in security group
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}" 
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: bastion_sg_out

    - name: Creating bastion host 
      ec2: 
        key_name: bastion_key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags: 
          Name: ansible_project
          Owner: Atdheoo
        exact_count: 1
        count_tag:
          Name: "bastion_host_sg"
          Project: ansible_project
          Owner: Atdheoo
        group_id: "{{ bastion_sg_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastion_host_out

    - name: Insert/Update "bastion_sg_id" in vars/vpc-output_vars
      blockinfile:
        path: vars/vpc-output_vars
        backup: yes
        block: | 
          bastion_sg_id: {{ bastion_sg_out.group_id }}
          