---
- name: Setup stack 
  hosts: localhost 
  connection: local
  gather_facts: no
  tasks:
    - name: Import vpc setup variable
      include_vars: vars/vpc-output_vars

    - name: Import setup variable
      include_vars: vars/stack_setup

    - name: Create ec2 key
      ec2_key:
        name: key_instance
        region: "{{ region }}"
      register: key_out

    - name: Save private key into file login_key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./login_key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create security group  for load balancer
      ec2_group:
        name: elb_sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: elb_out

    - name: Create security group for stack 
      ec2_group:
        name: stack_sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ elb_out.group_id }}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ bastion_sg_id }}"

